# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-29 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0064_auto_20210208_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='laddersettings',
            name='game_mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Captains Mode'), (1, 'Captains Draft')], default=0),
        ),
    ]
