# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-05-22 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0065_laddersettings_game_mode'),
        ('ladder', '0065_auto_20210405_1201'),
    ]

    operations = [
    ]
